import requests
import json
import time

url = "http://localhost:3000/api/nl2sql"
headers = {"Content-Type": "application/json"}

questions = [
    "Find employees who arrived late more than 3 times this week but still completed their total required work hours.",
    "Identify any employee who was present for less than 4 hours but consumed more than 2 canteen items.",
    "Show me the correlation between late arrivals and canteen usage for the IT department this month.",
    "Which room has the highest number of unique visitors (not employees) today?",
    "List employees who have 'Access Denied' events at the Server Room but have never been in the IT department.",
    "What is the most frequent purpose of visit for guests staying longer than 2 hours?",
    "Find the employee who has the most inconsistent arrival times (highest variance) this month.",
    "Show the total canteen revenue generated by employees who worked overtime yesterday.",
    "Identify any 'Access Denied' events that occurred within 10 minutes of a visitor checking in to the same host.",
    "Which shift has the highest average break time?",
    "List employees who have never used the canteen but have over 200 hours of work time this month.",
    "Find visitors who checked out after their host had already left for the day.",
    "Which day of the week has the highest average building occupancy?",
    "Compare the total break time of employees who arrived on time vs those who arrived late.",
    "What is the average time between an employee's ActualInTime and their first canteen punch?",
    "List the top 5 most frequently visited rooms by employees who have 'Manager' in their designation.",
    "Which host had visitors from the most unique companies this month?",
    "Show the average work time for employees based on the number of canteen items they consume.",
    "Identify employees who have an 'Access Granted' event but no ActualInTime punch for the day.",
    "What percentage of total canteen revenue comes from the top 10% of spenders?",
    "List employees who took breaks totaling exactly their allowed break time.",
    "Which department has the highest ratio of visitors to employees today?",
    "Compare the average canteen spend on days with overtime vs days without overtime."
]

results = []

for i, q in enumerate(questions):
    print(f"[{i+1}/{len(questions)}] Testing: {q}")
    try:
        response = requests.post(url, data=json.dumps({"prompt": q}), headers=headers)
        res_json = response.json()
        
        if response.status_code == 200 and res_json.get("success"):
            status = "PASS"
            results.append({
                "id": i+1,
                "question": q,
                "status": "PASS",
                "query": res_json.get("queryExecuted", "N/A")
            })
            print(f"  -> PASS")
        else:
            status = "FAIL"
            err_msg = res_json.get("details", str(res_json.get("error", "Unknown Error")))
            results.append({
                "id": i+1,
                "question": q,
                "status": "FAIL",
                "error": err_msg
            })
            print(f"  -> FAIL: {err_msg}")
    except Exception as e:
        results.append({"id": i+1, "question": q, "status": "ERROR", "error": str(e)})
        print(f"  -> ERROR: {str(e)}")
    
    with open("phase3_retry_failed_results.json", "w") as f:
        json.dump(results, f, indent=2)
    
    time.sleep(30)

print("\n--- PHASE 3 FAILED RETRY COMPLETE ---")
print(f"Total: {len(results)}, Passed: {len([r for r in results if r['status'] == 'PASS'])}")
